name: Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  release:
    types:
      - published

jobs:
  test:
    name: Test and Coverage
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.11
      - name: Install in dev mode and test
        run: |
          uv sync --group dev --config-setting editable_mode=strict -v
          uv run coverage run
          uv run coverage report -m
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  wheels-build:
    needs: [test]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-versions: [
          {version: '3.11', glob: cp311*},
          {version: '3.12', glob: cp312*},
          {version: '3.13', glob: cp313*},
          ]
    name: Python ${{ matrix.python-versions.version }} wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build wheel
        uses: pypa/cibuildwheel@v3.2.0
        env:
          CIBW_BUILD: ${{ matrix.python-versions.glob }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        run: uv python install ${{ matrix.python-versions.version }}
      - name: Test wheel
        run: |
          uv venv --python ${{ matrix.python-versions.version }} .venv-test
          uv pip install --python .venv-test/bin/python ./wheelhouse/*${{ matrix.python-versions.glob }}.whl pytest pybids
          uv run --no-project --python .venv-test/bin/python pytest --import-mode=append
      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}-cp${{ matrix.python-versions.version }}
          path: ./wheelhouse/*.whl
  sdist-build:
    needs: [test]
    name: Make sdist
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        run: uv python install 3.11
      - name: Build sdist
        run: uv build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
  py-publish:
    name: Publish to PyPI
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [wheels-build, sdist-build]
    runs-on: ubuntu-22.04
    environment:
      name: release
      url: https://pypi.org/project/warpkit/
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: dist
        merge-multiple: true
    - uses: pypa/gh-action-pypi-publish@release/v1
  docker-build:
    name: Build Docker image
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [wheels-build, sdist-build]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    environment:
      name: release
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/vanandrew/warpkit
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
